# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./dataBase/condition.h \
    ./dataBase/help.h \
    ./dataBase/kTable.h \
    ./dataBase/readSQL.h \
    ./dataBase/Save.h \
    ./dataBase/userDatabase.h \
    ./headClass.h \
    ./MainDataBase.h \
    ./MusicData.h \
    ./Ui_Test.h \
    ./UserData.h \
    ./WarningWindows.h \
    ./MainWindow.h \
    ./HelpWindow.h \
    ./tableview.h \
    ./UserWindow.h
SOURCES += ./dataBase/condition.cpp \
    ./dataBase/help.cpp \
    ./dataBase/kTable.cpp \
    ./dataBase/readSQL.cpp \
    ./dataBase/Save.cpp \
    ./dataBase/userDatabase.cpp \
    ./headClass.cpp \
    ./HelpWindow.cpp \
    ./main.cpp \
    ./MainDataBase.cpp \
    ./MusicData.cpp \
    ./MainWindow.cpp \
    ./tableview.cpp \
    ./Ui_Test.cpp \
    ./UserData.cpp \
    ./userwindows.cpp \
    ./WarningWindows.cpp
FORMS += ./MainWindow.ui \
    ./UserWindow.ui \
    ./HelpWindow.ui \
    ./tableview.ui
RESOURCES += qt_test.qrc
