# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./MainDataBase.h \
    ./MusicData.h \
    ./Ui_Test.h \
    ./UserData.h \
    ./WarningWindows.h \
    ./qt_test.h \
    ./userwindows.h \
    ./resource.h \
    $$PWD/helpwindows.h
SOURCES += ./main.cpp \
    ./MainDataBase.cpp \
    ./MusicData.cpp \
    ./qt_test.cpp \
    ./Ui_Test.cpp \
    ./UserData.cpp \
    ./userwindows.cpp \
    ./WarningWindows.cpp \
    $$PWD/helpwindows.cpp
FORMS += ./qt_test.ui \
    ./userwindows.ui \
    $$PWD/helpwindows.ui
RESOURCES += qt_test.qrc
